export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD'

export const CAMERA_UPDATE_FIELD = 'CAMERA_UPDATE_FIELD'

export const INVENTORIES_UPDATE_FIELD = 'INVENTORIES_UPDATE_FIELD'

export const NOTIFICATION_CREATE = 'NOTIFICATION_CREATE'
export const NOTIFICATION_DESTROY = 'NOTIFICATION_DESTROY'

export const PROVIDERS_UPDATE_FIELD = 'PROVIDERS_UPDATE_FIELD'

export const SHIPPINGS_UPDATE_FIELD = 'SHIPPINGS_UPDATE_FIELD'

export const STORES_UPDATE_FIELD = 'STORES_UPDATE_FIELD'
