# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Push a new beta build to TestFlight'
  lane :beta do
    increment_build_number(
      xcodeproj: 'Xanyah.xcodeproj',
      build_number: latest_testflight_build_number + 1
    )
    match(
      git_url: ENV['GIT_URL'],
      type: 'appstore'
    )
    gym(scheme: 'Xanyah')
    testflight
  end
end
