# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Runs all the tests'
  lane :test do
    gradle(task: 'test')
  end

  desc 'Submit Internal'
  lane :internal do
    increment_version_code(
      gradle_file_path: 'app/build.gradle'
    )
    gradle(task: 'assembleRelease')
    supply(track: 'internal')
  end

  desc 'Submit alpha'
  lane :alpha do
    supply(
      track: 'internal',
      track_promote_to: 'alpha',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc 'Submit beta'
  lane :beta do
    supply(
      track: 'alpha',
      track_promote_to: 'beta',
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc 'Deploy a new version to the Google Play'
  lane :deploy do
    gradle(task: 'assembleRelease')
    upload_to_play_store
  end
end
